#!/bin/bash
#SBATCH -p a100q    ## hgx2q, a100q,  dgx2q (old), xeonmaxq, and  genoaxq
#SBATCH --output=interestingoutput.out    ## Output file
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --ntasks-per-node=1
#SBATCH -c 8
#SBATCH -t 13-00:00 # time (D-HH:MM)
#SBATCH --mail-user=sanyamj@hiof.no

ulimit -s 10240
module purge 
module load slurm/21.08.8
# module load anaconda3/x86_64/2023.09-0    #  Latest anaconda3 installed
# module load miniconda3/py311/23.10.0-1    #  Latest miniconda3 installed

## module load cuda11.0/toolkit/11.0.3   # Suggest cuda12.2/toolkit/12.2.2
## module load cudnn8.0-cuda11.0         # Suggest cudnn8.9-cuda12.2/8.9.6.50
#module load cuda11.3/toolkit/11.3.0     # no longer installed
#module load cudnn8.0-cuda11.3           # no longer installed 
# module use  /cm/shared/ex3-modules/latest/modulefiles    
##module load slurm/20.02.7              # Current version is 21.08.8
##module load python-3.9.15              


# ACTIVATE ANACONDA
eval "$(conda shell.bash hook)"
source ../srhat_env/bin/activate                   # Which version
srun python train.py -opt options/train/train_Real_HAT_GAN_SRx4_finetune_from_mse_model.yml

